### ISSUE TITLE
0.0.22 Release

### ISSUE THREAD

**Issue by davidjgonzalez** [Adobe-Consulting-Services/acs-aem-tools#106]
Hey @justinedelson you cool w a 0.0.22 release this week?

@chetanmeh this has the Explain Query fixes as well (sorry for how long this has taken)

**Comment by justinedelson** [comment]
do you want to fix #82 first?

**Comment by davidjgonzalez** [comment]
82 should be fixed via .. https://github.com/Adobe-Consulting-Services/acs-aem-tools/commit/707fea0dfbe5cc98416ece1dec3bc283c4969b1a

Need to merge In csv asset importer the. We should be good- was waiting last night for Travis to go green and then got distracted by TV

**Comment by justinedelson** [comment]
release is done and up on repo.adobe.com (and bintray)

The only thing I didn't do is create the release on GitHub, but I'm not sure if anyone actually looks at that page :)

**Comment by rajeshp** [comment]
some people do look at this page :)

**Comment by justinedelson** [comment]
Good to know :). https://github.com/Adobe-Consulting-Services/acs-aem-tools/releases/tag/acs-aem-tools-0.0.22 now has some reasonable content on it

**Comment by sabyamon** [comment]
and there are more ppl :)
