### ISSUE TITLE
AEM LiveReload doesn't work when editing CSS files in the CRXDE

### ISSUE THREAD

**Issue by jonkemp** [Adobe-Consulting-Services/acs-aem-tools#108]
I have the extension installed for Chrome and Firefox. I am expecting to see changes on this page.

http://localhost:4502/content/geometrixx/en/products.html?wcmmode=disabled

I make a change here and save it.

http://localhost:4502/crx/de/index.jsp#/etc/designs/geometrixx/static.css

I still have to reload the browser manually to see the change. LiveReload is not working. According to the documentation:

>LiveReload can be leveraged when vlt’ing files into CRX, deploying via Maven builds or editing in CRXDE/CRXDE Lite.

**Comment by justinedelson** [comment]
This is not a supported use case. Per http://adobe-consulting-services.github.io/acs-aem-tools/features/live-reload.html, only resource scripts and client library changes are supported (and the latter only on 6.0 and above). `/etc/designs/geometrixx/static.css` isn't part of a client library. Support for this could be added (patches welcome of course), but I'd really suggest you use client libraries instead.

**Comment by jonkemp** [comment]
Ah, I see that now. So what constitutes a 'client library' exactly?

**Comment by davidjgonzalez** [comment]
@jonkemp  He means that the CSS or JS request must be served through a `cq:ClientLibraryFolder` resource.

IMO using static files is a bit of an anti-pattern (even/especially the OOTB static.css).

For a nice, flexible approach to ClientLibs on your projects checkout ... http://adobe-consulting-services.github.io/acs-aem-commons/features/designer-clientlibsmanager.html

**Comment by jonkemp** [comment]
Thank you for your help!
