### ISSUE TITLE
JCR Checksum Compare

### ISSUE THREAD

**Issue by davidjgonzalez** [Adobe-Consulting-Services/acs-aem-tools#111]
A tool to compare hash of JCR trees to determine if they are the same or different.

**Comment by davidjgonzalez** [comment]
@justinedelson and @andrewmkhoury - should this be in commons or tools? Keeping in mind, officially tools shouldnt be installed on Prod.

**Comment by andrewmkhoury** [comment]
I have no idea on how you guys manage the projects.  I leave this decision up to @justinedelson.
-Andrew

**Comment by davidjgonzalez** [comment]
It feels like a tool but the use case is 90% prod, so suppose commons is the better place. Closing this issue so we can move to commons; @justinedelson feel free to add your 2 cents

**Comment by justinedelson** [comment]
I agree. I'd go further and say that the *primary* use for this is in production :)
