### ISSUE TITLE
500 when creating task in vlt-rcp tool

### ISSUE THREAD

**Issue by kalyanar** [Adobe-Consulting-Services/acs-aem-tools#112]
The error is "/libs/granite/packaging/rcp" is not found. This occurs in 6.1

**Comment by davidjgonzalez** [comment]
@kalyanar Can you verify that you installed the jackrabbit vlt-rcp service bundle? This end point is part of the jackrabbit vlt-rcp bundle (which i dont believe is bundled in AEM6.1 -- correct me if im wrong on that /cc @justinedelson )

See download line at top of: https://adobe-consulting-services.github.io/acs-aem-tools/vlt-rcp.html

**Comment by kalyanar** [comment]
I did.

**Comment by kalyanar** [comment]
When I replaced the rcp_uri (/libs/granite/packaging/rcp) with /system/jackrabbit/filevault/rcp, it started working.

**Comment by davidjgonzalez** [comment]
Can you provide a link to the vlt-rcp bundle you're using?

The app in acs tools should check the new uri and the legacy uri..

**Comment by kalyanar** [comment]
I used 3.1.18. When I forked the code, it did not show any servlet registered at /libs/granite/packaging path.

http://mvnrepository.com/artifact/org.apache.jackrabbit.vault/org.apache.jackrabbit.vault.rcp/3.1.18

**Comment by davidjgonzalez** [comment]
Forked which code? The acs tools code?

**Comment by kalyanar** [comment]
I looked in https://github.com/apache/jackrabbit-filevault

**Comment by davidjgonzalez** [comment]
Found the commit where it changed ... https://github.com/apache/jackrabbit-filevault/commit/b0ccc74fdf98038b1680477b9d5724337102681f

If you want to add a pr to add the new path to the rcp_uris that'd be awesome! Newest should be the default as well. If not, I can do it this week!

Thanks for reporting this!

**Comment by davidjgonzalez** [comment]
Actually - the old one iis already in the list -- the tool should try both on start up. It will give a non 200 response for the path that doesn't exist though this doesn't mean it's broken,

**Comment by kalyanar** [comment]
ngdialog doesnt seem to be updated with new $scope values. When I added {{rcp_uri}} within the create task dialog, it was still showing the default scope.rcp_uri value.

**Comment by davidjgonzalez** [comment]
What version of acs tools? In newest ng-dialog is not used; coralui modal is instead

**Comment by kalyanar** [comment]
When I clicked on the download link, I got 0.0.22.

**Comment by kalyanar** [comment]
will coralui modal also work in 5.6.1? I m trying to evaluate this to migrate repo from 5.6.1 to 6.1.

**Comment by justinedelson** [comment]
CUI 1.x should work basically the same in 5.6.1 through 6.1

**Comment by davidjgonzalez** [comment]
@kalyanar did you get this resolved?I am testing it out and latest build works fine w 
![2015-10-29 at 6 15 pm](https://cloud.githubusercontent.com/assets/1451868/10833553/201a6442-7e69-11e5-950b-755146cbbeb8.png)
org.apache.jackrabbit.vault.rcp-3.1.18.jar

**Comment by kalyanar** [comment]
@davidjgonzalez I m closing this issue as it works fine now for me. Thanks a lot.
