### ISSUE TITLE
New tool: sling-pipes

### ISSUE THREAD

**Issue by dlh3** [Adobe-Consulting-Services/acs-aem-tools#121]
I recently came across npeltier/sling-pipes (https://github.com/npeltier/sling-pipes).  This seems like an excellent tool for performing transformations on JCR data.  Unfortunately, it did not seem to work with AEM (5.6.1; have not tried with 6).

I would love to see this forked/inherited as an ACS-AEM-Tool.

**Comment by kwin** [comment]
This is about to be donated to Apache Sling (https://issues.apache.org/jira/browse/SLING-5134) so no need for a fork.

**Comment by dlh3** [comment]
Oh, that's wonderful.  How long will it take for that to become available in AEM, though?

Once it is available, it would be great if this project included a tool that provides a UI to sling-pipes (npeltier/sling-pipes#5).

**Comment by cwoeltge** [comment]
Maybe it won't help you on 5.6.1 - compatibility says "java 8 (Nashorn is used for expression)" https://github.com/npeltier/sling-pipes#compatibility

**Comment by dlh3** [comment]
Yes, I am aware.  I spent some time yesterday making the project Java 7 compatible (stripping out certain parts that were not necessary for my use case).

Specifically, it was the [sling-distribution](https://github.com/npeltier/sling-pipes/blob/master/src/main/java/org/apache/sling/pipes/impl/PlumberImpl.java#L132-L141) part that I was not familiar enough to rewrite for our use case.

**Comment by justinedelson** [comment]
@dlh3 sling distribution ships with AEM 6.1. I'm not sure if you can install it on older versions, but it is certainly worth a shot.
