### ISSUE TITLE
It do not seems to work in AEM 6.1 .

### ISSUE THREAD

**Issue by sunilcemk06** [Adobe-Consulting-Services/acs-aem-tools#123]
Can we update this to work in AEM 6.1, as by default the compiled classes are no longer available in /var/classes folder ?

**Comment by davidjgonzalez** [comment]
@sunilcemk06 what tool is breaking? JSP Code Display [1]?

[1] https://adobe-consulting-services.github.io/acs-aem-tools/jsp-code-display.html

**Comment by justinedelson** [comment]
I'm assuming this is related to the JSP Code Display feature. If it is something else, please reopen.

**Comment by joerghoh** [comment]
Just for the record: AEM 6.0 SP3 uses FSClassloader too.
