### ISSUE TITLE
CSV Asset Importer is not working

### ISSUE THREAD

**Issue by sameryadav** [Adobe-Consulting-Services/acs-aem-tools#131]
Hi

I am using the below acs-aem-tool code and trying to uoload the assets. but it is not working and throwing the error like the absTargetPath and relSrPath not found.

Code: https://github.com/Adobe-Consulting-Services/acs-aem-tools
Uploaded screen shout of csv file and below are the data as well:

absTargetPath,relSrcPath,uid,dc:title{{String:multi}},dc:description{{String:multi}}
/content/dam/demo/document-1.jpg,document-1.jpg,1000,Sandhu,This is test

![test](https://cloud.githubusercontent.com/assets/6961852/13125604/72f4e728-d594-11e5-87cd-2b027d0be14b.PNG)

**Comment by davidjgonzalez** [comment]
can you attach the actual CSV file please? FWIW when you imported this into Excel you didnt split on commas, so if you were to export to CSV again it would be a bad CSV file.

**Comment by sameryadav** [comment]
please find attached csv file

**Comment by sameryadav** [comment]
Hi David,

Did you received the attached CVS file?

Thanks
Samer

**Comment by davidjgonzalez** [comment]
I dont see the file in the comments.. doesnt look like it was uploaded

**Comment by sameryadav** [comment]
[test.txt](https://github.com/Adobe-Consulting-Services/acs-aem-tools/files/135242/test.txt)

Please find attached one and rename it with .csv extension

**Comment by davidjgonzalez** [comment]
Your CSV file is not a valid CSV .. its all 1 big column. Open then text file, you have double quotes around each line.

**Comment by sameryadav** [comment]
no no..in CSV it is not doble quotes..actually i am not able to attache the CSV file thats why I renamed it in .txt filr to sent you. Please share me you email address so that I can sent you the original csv file

**Comment by sameryadav** [comment]
when i an attaching here then getting error as below:
Unfortunately, we don’t support that file type.  Choose Files Try again with a PNG, GIF, JPG, DOCX, PPTX, XLSX, TXT, PDF, or ZIP.

**Comment by sameryadav** [comment]
great news I am able to upload it now it is working fine...

Thanks David for your valuable input.

**Comment by sameryadav** [comment]
One more question
so this tool will only import from csv file right?
Actually we have the data in to xml file the Do we need to convert first in to csv then we can upload it right?

**Comment by davidjgonzalez** [comment]
This only works for CSV files
