### ISSUE TITLE
Tag Maker in multiple languages

### ISSUE THREAD

**Issue by adolfodepazvela** [Adobe-Consulting-Services/acs-aem-tools#133]
Hello ! 
I just write a new Data Converter that handle multiple titles in different languages, I wonder if I can share my code to contribute?

Basically the Data Converter use this format `en[my title] fr[mon titre] es[Mi titulo] {{ my-title }}`  to create tags, is based on the Title {{ node-name }} converter.

**Comment by justinedelson** [comment]
yes. see https://github.com/Adobe-Consulting-Services/acs-aem-commons/blob/master/CONTRIBUTING.md for details

**Comment by adolfodepazvela** [comment]
Yes I saw the instructions, but looks like I have no right to push my
changes!

thanks
Adolfo

**Comment by justinedelson** [comment]
right, as it says there you need to create your own fork and push to that fork and then create a pull request. More information can be found in https://help.github.com/articles/using-pull-requests (which is linked to from that page)

**Comment by davidjgonzalez** [comment]
Closed via #135
