### ISSUE TITLE
CSV Asset Importer - Value type switching prevents property persistence

### ISSUE THREAD

**Issue by davidjgonzalez** [Adobe-Consulting-Services/acs-aem-tools#141]
by way of @harrington101 

If a value is persisted a String property in the JCR, and the CSV Asset Importer column definition is {{ String : multi }} (or vice versa) the property persistence will fail.

**Comment by davidjgonzalez** [comment]
@harrington101  Check you check out the following build and see if it fixes?

[acs-aem-tools-content-0.0.27-SNAPSHOT-min.zip](https://github.com/Adobe-Consulting-Services/acs-aem-tools/files/298531/acs-aem-tools-content-0.0.27-SNAPSHOT-min.zip)

**Comment by bstopp** [comment]
@davidjgonzalez It's the Resource resolver being pulled from the Request; if you start up a new one from a factory; works fine (or in this code, clone it: https://github.com/bstopp/acs-aem-tools/tree/bug/csv-asset-importer/multi-v-single-prop)

**Comment by davidjgonzalez** [comment]
Any idea why the requests doesn't work? That seem strange..

**Comment by bstopp** [comment]
Not sure. Want a PR or want me to clean up the fix some?

**Comment by bstopp** [comment]
Actually that code doesn't work as i thought; it's not changing the type either.

**Comment by davidjgonzalez** [comment]
@bstopp thanks for fixing. Making a separate issue for property type switching.

Closed via #142

**Comment by harrington101** [comment]
Thanks, David. Do you have a download link for installing this latest fix?

**Comment by bstopp** [comment]
No release yet, but if you clone & build the master you'll be good to go.

**Comment by harrington101** [comment]
I'm not familiar with that process. I'll wait for the release.

**Comment by davidjgonzalez** [comment]
@harrington101 try this .. includes the property type switching too (String -> Long) as well as single to multi (and vice versa)

[acs-aem-tools-content-0.0.27-SNAPSHOT-min.zip](https://github.com/Adobe-Consulting-Services/acs-aem-tools/files/302644/acs-aem-tools-content-0.0.27-SNAPSHOT-min.zip)

**Comment by harrington101** [comment]
Thanks but unfortunately that build undoes the previous fix that allows uploading of metadata to existing images rather than to new ones. The absolute file dump location becomes a required field again.

**Comment by davidjgonzalez** [comment]
@harrington101 really? I uploaded that zip to a fresh instance and uploaded an update file (just a target path and dc:title) and it worked..

![2016-06-07 at 12 42 pm](https://cloud.githubusercontent.com/assets/1451868/15866642/8c3d6e1a-2cad-11e6-9437-49f73e1d63ea.png)

Can you try uninstalling your ACS Tools package and re-installing? You could even try deleting the bundle manually... something fishy is going on for you i think.

**Comment by davidjgonzalez** [comment]
@harrington101 any luck?

**Comment by harrington101** [comment]
Hi David,

Uninstalling and deleting the package and then reinstalling did the trick. This seems to be working. Thank you so much for your and bstopp's help.

**Comment by davidjgonzalez** [comment]
@harrington101 thank you for taking the time to help validate; its very appreciated!
