### ISSUE TITLE
Put a sample csv file in the CSV Asset Importer documentation

### ISSUE THREAD

**Issue by rajeshp** [Adobe-Consulting-Services/acs-aem-tools#152]
@davidjgonzalez @justinedelson 

The CSV Asset importer documentation is good but it will be much helpful if a sample csv file is provided. The structure of csv file(columns) which is accepted as input is a bit confusing and hard to figure out by just reading the documentation.

**Comment by davidjgonzalez** [comment]
@rajeshp this was done a while ago; closing. If you have a more robust CSV sample file please feel free to contribute (attach tot his comment and i can move it over to docs page)
