### ISSUE TITLE
VLT RCP UI should mask or prompt for passwords

### ISSUE THREAD

**Issue by thedoc31** [Adobe-Consulting-Services/acs-aem-tools#156]
When creating a new task, the VLT RCP UI source field should either prompt for passwords or mask them rather than showing them or allowing them to be entered in plain text.

**Comment by davidjgonzalez** [comment]
BTW - this tool is just a web front end for vlt-rcp [1], we just construct the HTTP requests - nothing is persisted on the server. So the credentials (which are now password field) are never send to the server and only exist on your browser for the life of the page load, or when the web front makes a call to the vlt-rcp end point and displays the resulting JSON (which sends the pword plaintext).

We now mask the password out with "******" in #166 

I think this is the best we can do in the ACS Tools project side, please reopen if you disagree.

[1] http://jackrabbit.apache.org/filevault/rcp.html
