### ISSUE TITLE
multilingual tag maker

### ISSUE THREAD

**Issue by oswjos** [Adobe-Consulting-Services/acs-aem-tools#157]
Hi guys,

Thanks for the awesome feature Tag Maker! 

I would like Tag Maker to also be able to handle multilingual tags. I've attached an excel file where I wrote a sample excel of tags with titles in multiple languages. Basically I just added a few more columns where I wrote the title in the foreign language as well as the locale inside curly brackets {{ }}. This format is totally open to improvements if someone can think of a better/easier way for users to write down their multilingual tags' taxonomy.

Hope to hear from you guys soon.

Thanks a bunch,

何塞。

![image](https://cloud.githubusercontent.com/assets/1451868/17709341/b9194d06-63b6-11e6-8a58-6f2bfb34e15a.png)

[multilingual-tag-maker.xlsx](https://github.com/Adobe-Consulting-Services/acs-aem-tools/files/419440/multilingual-tag-maker.xlsx)

**Comment by davidjgonzalez** [comment]
@oswjos thanks for the enhancement idea.. 

![image](https://cloud.githubusercontent.com/assets/1451868/17699822/f7c54c56-6390-11e6-88f5-db4fada0a456.png)

Wrt to the Excel (CSV) layout ... i think having them post-fixed at the end could become confusing (are those themselves tags? If there is a fallback processor they'd bet treated as such, etc.)

WDYT about something like...

![image](https://cloud.githubusercontent.com/assets/1451868/17700082/4d0f22b2-6392-11e6-8eea-936b3e86f91d.png)

Then each tag could define its own set of locales titles?

**Comment by oswjos** [comment]
You are right, that kinda formatting would be acceptable as well. Hopefully the tag maker can make multilingual tags soon :)

**Comment by justinedelson** [comment]
@davidjgonzalez in your example, what would the tag's node name be?

**Comment by davidjgonzalez** [comment]
@justinedelson  :) .. lets try that again ..

![image](https://cloud.githubusercontent.com/assets/1451868/17707969/c6dd6a7c-63b0-11e6-8691-63d23d3ce104.png)

I wonder if it makes sense to have this support any arbitrary property on the tag... 

![image](https://cloud.githubusercontent.com/assets/1451868/17708041/229c853c-63b1-11e6-9932-4754e941ab23.png)

Probably needs a better prop:value delimiter than `:` ...

**Comment by davidjgonzalez** [comment]
the more i think about it - I do like that @oswjos breaks out the values into their own columns, constructing the delimited key:value pairs is likely annoying and harder to do for a biz user - there has to be someway to denote what is a path, and what is a property through .. 

i loathe to add the complexity of csv asset importer's column based approach to tag maker though ...

**Comment by davidjgonzalez** [comment]
Ok .. so, totally forgot this was added (never made it to the docos) ...

Multi-lingual titles can be set via: the `LocalizedTitleAndNodeNameConverter` using this pattern `en[Title] fr[Titre] es[Titulo] {{ node-name }}`
