### ISSUE TITLE
Version 0.0.30 is not available through Adobe Repo

### ISSUE THREAD

**Issue by kwin** [Adobe-Consulting-Services/acs-aem-tools#161]
In the past all releases were available from the Adobe repo at https://repo.adobe.com/nexus/content/groups/public/com/adobe/acs/acs-aem-tools-content/. The newest version though is 0.0.28. Could you publish 0.0.30 to the Adobe repo as well?

**Comment by davidjgonzalez** [comment]
@kwin Requested the deployment.  Will leave open until the deployment is complete.

thanks!

**Comment by davidjgonzalez** [comment]
Done
