### ISSUE TITLE
VLT RCP does not work via ACS Tools v0.0.30 and VLT RCP 3.1.30

### ISSUE THREAD

**Issue by davidjgonzalez** [Adobe-Consulting-Services/acs-aem-tools#162]
*ERROR* POST /system/jackrabbit/filevault/rcp HTTP/1.1] org.apache.jackrabbit.vault.rcp.impl.RcpTask Error while logging in src repository http://admin:admin@localhost:4502/crx/server/-/jcr:root/content/dam/my-site: javax.jcr.lock.LockException: Precondition Failed

**Comment by jayproulx** [comment]
I'm seeing the same issue, same version of vault-cli

**Comment by nadendlaraviteja** [comment]
any update on the issue? I am getting the same error.

**Comment by davidjgonzalez** [comment]
Your running into this issue.. 

Please change the source to explicitly specify the workspace... so, change:


Source: `http://admin:admin@localhost:4502/crx/server/-/jcr:root/content/dam/we-retail`

to 

Source: `http://admin:admin@localhost:4502/crx/server/crx.default/jcr:root/content/dam/we-retail`
