### ISSUE TITLE
com.adobe.acs.acs-aem-tools-bundle needs to resolve with com.day.cq.widget 6.0+

### ISSUE THREAD

**Issue by chibulcuteanu** [Adobe-Consulting-Services/acs-aem-tools#168]
Currently com.adobe.acs.acs-aem-tools-bundle 0.0.30 is not compatbile with AEM 6.3 L16 which includes com.day.cq.widget-6.0.

Because of this ACS AEM Tools Bundle remains in installed state with the following dependency not being resolved: com.day.cq.widget,version=[5.5,6) -- Cannot be resolved

**Comment by justinedelson** [comment]
I've pushed a change to make this import optional until we can figure out a sustainable solution.
