### ISSUE TITLE
Angular js 1.6.1 showing syntax error while minifying with AEM 6.1 with SP2

### ISSUE THREAD

**Issue by Tewari1005** [Adobe-Consulting-Services/acs-aem-tools#174]
I am facing issue  during minification of angular js using AEM OTB functionality that it throwing 404. We are receiving 34 syntax error in error.log file. We are using AEM 6.1 with SP2 and angular version is 1.6.1. Any one who have minified this angular JS version for AEM 6.1 ,please share it over mail(tewari.b34991@gmail.com) or here . This will help us a lot
waitng for response

**Comment by justinedelson** [comment]
in what way is this related to the ACS AEM Tools project?

**Comment by Tewari1005** [comment]
Ya I know it is not related to acs common project. 
I thought might any of this project have did it that will help us..
