### ISSUE TITLE
Not able to connect to repo via vlt-rcp : error  Connection refused

### ISSUE THREAD

**Issue by yogesh-kulkarni** [Adobe-Consulting-Services/acs-aem-tools#175]
using GUI http://localhost:4503/etc/acs-tools/vlt-rcp.html - 
trying to connect to http://admin:admin@localhost:4502/crx/server/-/jcr:root/content/my/sample
seeing following error :
1.03.2017 01:42:29.317 *ERROR* [10.0.2.2 [1488332549308] POST /system/jackrabbit/filevault/rcp HTTP/1.1] org.apache.jackrabbit.vault.rcp.impl.RcpTask Error while retrieving src repository http://admin:admin@localhost:4502/crx.default/-/jcr:root/content/my/sample : javax.jcr.RepositoryException: java.net.ConnectException: Connection refused
01.03.2017 01:42:29.318 *ERROR* [10.0.2.2 [1488332549308] POST /system/jackrabbit/filevault/rcp HTTP/1.1] org.apache.jackrabbit.vault.rcp.impl.RcpServlet Error while executing command start
javax.jcr.RepositoryException: java.net.ConnectException: Connection refused

Running on AEM 6.1
org.apache.jackrabbit.vault.rcp - 	3.1.30

Does anyone run into the same problem ?

**Comment by rmatteoda** [comment]
I have the same issue. could you fix it?

**Comment by davidjgonzalez** [comment]
@rmatteoda this is an issue w vlt or oak, to work around update your src to:

 http://admin:admin@localhost:4502/crx/server/**crx-default**/jcr:root/content/my/sample

**Comment by rmatteoda** [comment]
@davidjgonzalez now I get a precondition failed error
