### ISSUE TITLE
how to build the development environment  like acs-aem-tools?

### ISSUE THREAD

**Issue by lx171717** [Adobe-Consulting-Services/acs-aem-tools#183]
I want to  custom the acs-aem-tools

**Comment by justinedelson** [comment]
there is a building section in the README. If this doesn't work, feel free to reopen with the specific problem you are having.

**Comment by lx171717** [comment]
Thanks very much  for your reply, but I only find below section
Building

This project uses Maven for building. Common commands:

From the root directory, run mvn -PautoInstallPackage clean install to build the bundle and content package and install to a CQ instance.

From the bundle directory, run mvn -PautoInstallBundle clean install to build just the bundle and install to a CQ instance.

**Comment by lx171717** [comment]
QA1, development tool is eclipse?
QA2, which  is eclipse plugin need to be install?
QA3, how to create a new project about  like acs-aem-tools projects.

**Comment by justinedelson** [comment]
No specific IDE is required to build ACS AEM Tools. The only requirement,
as stated in the README is Maven.
