### ISSUE TITLE
 QA about development environment like create acs-aem-tools project

### ISSUE THREAD

**Issue by lx171717** [Adobe-Consulting-Services/acs-aem-tools#185]
Thanks very much for your reply, but I only find below section in the README
**Building
This project uses Maven for building. Common commands:

From the root directory, run mvn -PautoInstallPackage clean install to build the bundle and content package and install to a CQ instance.

From the bundle directory, run mvn -PautoInstallBundle clean install to build just the bundle and install to a CQ instance.**

QA1, development tool is eclipse?
QA2, which is eclipse plugin need to be install?
QA3, how to create a new project about like acs-aem-tools projects.

**Comment by lx171717** [comment]
QA4, acs-aem-tools, 
acs-aem-tools-bundle,
acs-aem-tools-bundle-livereload, 
acs-aem-tools-content

how to create above project in the eclipse?

**Comment by justinedelson** [comment]
As I wrote in #183, Eclipse is not required to build ACS AEM Tools.

There are a variety of ways to create new AEM projects. I would suggest that you read the AEM documentation. You can also take a look at https://github.com/Adobe-Consulting-Services/lazybones-aem-templates

Please do not ask general AEM questions in ACS AEM Tools issues. This is specifically for reporting issues related to this project.
