### ISSUE TITLE
acs-aem-tools-bundle-livereload 0.0.40

### ISSUE THREAD

**Issue by vpetcu** [Adobe-Consulting-Services/acs-aem-tools#191]
acs-aem-tools-bundle-livereload 0.0.40 bundle which is reported to be compatible with AEM 6.3 has unresolved import range to com.day.cq.widget,version:
com.day.cq.widget,version=[5.5,6) -- Cannot be resolved

I think it should be recomipled to use the latest 6.x version of the import range.

**Comment by ravinderkp** [comment]
Is there any resolution of the above error?

**Comment by royteeuwen** [comment]
same issue here

**Comment by royteeuwen** [comment]
Sorry to poke again, but seeing as we are in process of upgrading and don't want to use the snapshot version, could you maybe release it @davidjgonzalez ?

**Comment by davidjgonzalez** [comment]
@royteewun might have time this weekend if that works ... I think this next build will break 6.0/6.1 support as well (since the fiddle fix needs to go in)

**Comment by justinedelson** [comment]
this was fixed in the 0.0.50 release
