### ISSUE TITLE
ACS Tools v0.0.52 OR v1.0.0 Release

### ISSUE THREAD

**Issue by davidjgonzalez** [Adobe-Consulting-Services/acs-aem-tools#196]
@justinedelson a new release of ACS Tools that works w/ AEM 6.3 would be good.

We haven been create w semantic version for ACS Tools; WDYT about taking this opportunity to align? This next release would be 1.0.0 since #170/#194 breaks AEM Fiddle support prior to 6.2.

We could follow suit and make a `compat/6.1` (since 6.0 dropped off in v0.0.30).

WDYT?

---

Also, i'm not sure what happened w v0.0.50 - the release is in Draft in Github? Is this supposed to be released or not?

**Comment by justinedelson** [comment]
I honestly don't know what happened with 0.0.50.

From my perspective, the value (such as it is) of having a < 1.0.0 version is that it reflects that this project is fairly unstable. That said, things seem to have stabilized somewhat, so I would be in favor of the next release being 1.0.0
