### ISSUE TITLE
ACS AEM Tools - Possible Copy Paste ?

### ISSUE THREAD

**Issue by Vitraag** [Adobe-Consulting-Services/acs-aem-tools#202]
As suggested by David Gonzalez on Linkedin, raising an issue here for tracking

![acs aem tools](https://user-images.githubusercontent.com/709907/32254680-7547fb6c-bef6-11e7-8a56-3852a9e4820b.png)

**Comment by davidjgonzalez** [comment]
Fixed - thanks!
