### ISSUE TITLE
VLT-RCP: Create N tasks from a workflow

### ISSUE THREAD

**Issue by danielrndm** [Adobe-Consulting-Services/acs-aem-tools#203]
Is there an option to create and start several tasks from a workflow?

We need to run the same 5 tasks to multiple instances. Instead of creating those tasks manually, we would like to define a workflow that rolls those tasks. Any ideas?

**Comment by davidjgonzalez** [comment]
@danielrndm Hi - im not sure i follow. the ACS Tools VLT-RCP feature is just a Web front-end for the Jackrabbit vlt-rcp tooling.

Are you saying you want your AEM Workflow to create/start VLT-RCP tasks?  If you want to do this, i think you'd have to write a AEM Workflow Process step that makes HTTP calls to the vlt-rcp end-points that will manage/run the tasks; I assume the WF would run on AEM Author, and then the AEM WF would tell AEM Pubs to pull data? Can you not use replication/packages to perform this work? 

ACS Commons has a nice feature that helps facilitate automatic package-based movement of content: https://adobe-consulting-services.github.io/acs-aem-commons/features/automatic-package-replicator/index.html

Please re-open this issue if i misunderstand the question. thanks!
