### ISSUE TITLE
ACS Tools - Fiddle script page not loading 

### ISSUE THREAD

**Issue by ukrsuresh** [Adobe-Consulting-Services/acs-aem-tools#210]
Hi,

I have acs-tools 0.0.52 installed on AEM 6.4.2(vanilla install with no custom code) and when i open any of the tools pages like AEM Fiddle, Explain Query or any other page under tools, pages are not loading properly.
On AEM Fiddle page, page header section is not loading where "Run code" button is available. I am unable execute any JSP code due to this issue. Same type of issues for all other tools pages also. 

Did anyone encountered these kind of issues and is there any update available to resolve this issue?

Also no luck with updating to latest acs-tools version 1.0.0.

![image](https://user-images.githubusercontent.com/45050511/48515411-a0e06400-e82e-11e8-8738-a669623fb903.png)

I see following error in the error log.

14.11.2018 16:45:38.055 *INFO* [0:0:0:0:0:0:0:1 [1542231938053] GET /home/users/2/20yEpuChGPTgNK_GRtT5/profile/fiddles.1.json HTTP/1.1] org.apache.sling.engine.impl.SlingRequestProcessorImpl service: Resource /home/users/2/20yEpuChGPTgNK_GRtT5/profile/fiddles.1.json not found
14.11.2018 16:46:08.377 *INFO* [0:0:0:0:0:0:0:1 [1542231968369] GET /home/users/2/20yEpuChGPTgNK_GRtT5/profile/fiddles.1.json HTTP/1.1] org.apache.sling.engine.impl.SlingRequestProcessorImpl service: Resource /home/users/2/20yEpuChGPTgNK_GRtT5/profile/fiddles.1.json not found
14.11.2018 16:46:38.787 *INFO* [0:0:0:0:0:0:0:1 [1542231998785] GET /home/users/2/20yEpuChGPTgNK_GRtT5/profile/fiddles.1.json HTTP/1.1] org.apache.sling.engine.impl.SlingRequestProcessorImpl service: Resource /home/users/2/20yEpuChGPTgNK_GRtT5/profile/fiddles.1.json not found

Thanks in advance.
Suresh

**Comment by davidjgonzalez** [comment]
yup - confirmed as a bug (wow - i havent used this in ages i guess!)

**Comment by davidjgonzalez** [comment]
luckily it looks to be cosmetic - if you write some code and hit cmd-k in macOS, ctrl-k in windows, it will execute the code (thats the shortcut to clicking execute)

**Comment by ukrsuresh** [comment]
Thanks Dave. Shortcut executes the code, but unfortunately results are not being displayed.

**Comment by davidjgonzalez** [comment]
Fixed in v1.0.2 (which is now released)
