### ISSUE TITLE
Tag Maker documentation should call out deprecation

### ISSUE THREAD

**Issue by himanshu-pathak** [Adobe-Consulting-Services/acs-aem-tools#214]
ACS Commons Tag Creator [documentation](https://adobe-consulting-services.github.io/acs-aem-commons/features/mcp-tools/tag-creator/index.html) claims to replace Tag Maker.

The Tag Maker [documentation](https://adobe-consulting-services.github.io/acs-aem-tools/features/tag-maker/index.html) should also call out the deprecation and add a link to Tag Creator page.

**Comment by davidjgonzalez** [comment]
Done - thanks. i also marked as deprecated (to favor acs aem commons)

https://adobe-consulting-services.github.io/acs-aem-tools/features/tag-maker/index.html
