### ISSUE TITLE
VLT-RCP - Stopping with exception javax.jcr.nodetype.ConstraintViolationException

### ISSUE THREAD

**Issue by sujeetsharma1980** [Adobe-Consulting-Services/acs-aem-tools#215]
org.apache.jackrabbit.vault.util.RepositoryCopier Error during intermediate save (1118); try again later: javax.jcr.nodetype.ConstraintViolationException: OakConstraint0021: /content/dam/test/rep:policy/deny11[[rep:DenyACE]]: Mandatory property rep:privileges not found in a new node.

Not sure why we are getting this exception. We are using AEM version 6.4 with service pack 2.

**Comment by davidjgonzalez** [comment]
This sounds like an issue with vlt-rcp itself rather than this web front end for it. Try reaching out to the vlt team.
