### ISSUE TITLE
VLT-RCP - Stopping with exception javax.jcr.InvalidItemStateException: OakState0001

### ISSUE THREAD

**Issue by sujeetsharma1980** [Adobe-Consulting-Services/acs-aem-tools#216]
org.apache.jackrabbit.vault.util.RepositoryCopier Error during intermediate save (2417); try again later: javax.jcr.InvalidItemStateException: OakState0001: Unresolved conflicts in /content/dam/test/ncal/clib/news/phase/jcr:content/folderThumbnail 
06.06.2019 14:26:13.443 *INFO* [NoRequestId] [Vault RCP Task - migrate ncal asset content-new-copy] org.apache.jackrabbit.vault.rcp.impl.RcpTask Intermediate saving 2418 nodes (42041 kB)

We are using version 6.4 with service pack 2

**Comment by davidjgonzalez** [comment]
This sounds like an issue with vlt-rcp itself rather than this web front end for it. Try reaching out to the vlt team.
