### ISSUE TITLE
Angularjs does not load when HTML Library manager minification enabled

### ISSUE THREAD

**Issue by davidjgonzalez** [Adobe-Consulting-Services/acs-aem-tools#40]
Aem 5.6.1 - observed /etc/clientlibs/acs-commons/angularjs.min.js 404s - disabling minification in HTML library manager resolves the issue.

**Comment by sbmadhav** [comment]
The html still wont load. Too many script errors.

**Comment by davidjgonzalez** [comment]
@sbmadhav what version of AEM and ACS Tools, and what specific Feature(s) do you see this on?

**Comment by sbmadhav** [comment]
@davidjgonzalez  : This issue is resolved. It was'nt to do with the angular.min.js.

**Comment by davidjgonzalez** [comment]
Can you share the cause of the issue and resolution?

**Comment by sbmadhav** [comment]
@davidjgonzalez : the issue was with use of incorrect import which was overseen due to large codebase. Nothing to do with Angular or AEM.

**Comment by davidjgonzalez** [comment]
Thanks for keeping us posted!

**Comment by Tewari1005** [comment]
HI All,

I am facing same issue that during minification of angular js using AEM OTB functionality we are receiving 34 syntax error in error.log file. We are using AEM 6.1 with SP2 and angular version is 1.6.1. Any one who have minified this angular JS version for AEM 6.1 ,please share it over mail(tewari.b34991@gmail.com) or here . This will help us a lot

**Comment by Shashi-Bhushan** [comment]
@Tewari1005 
Firstly you need to check on your console, for which clientlibs there is minification error. Then, you need to check individually what could be the error in individual JS files (of the clientlib where you got the error).
I upload my JS files individually on http://yui.2clics.net/ and it gives me error while compressing using YUI compression.
